baseURL = 'https://ispiroglu.github.io/'
languageCode = 'en-us'
title = 'Evren Ispiroglu'
theme = 'novela'
enableEmoji = true

[pagination]
  pagerSize = 5

description = "Evren Ispiroglu's personal blog"
homepage = "https://ispiroglu.github.io/"
tags = ["blog"]
features = ["dark mode", "grid view"]

[social]
  twitter= "https://twitter.com/eispirogluu"
  github="https://github.com/ispiroglu"
  linkedin= "https://www.linkedin.com/in/eispiroglu/"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 0


[taxonomies]
    tag = "tags"
    author = "authors"
    preserveTaxonomyNames = true


[permalinks]
    post = "/blog/:title/"
